### ISSUE TITLE
Action Not Yet Learned Spam

### ISSUE THREAD

**Issue by LTS-FFXIV** [FFXIV-CombatReborn/RotationSolverReborn#85]
Level 56 DRK during class quest to unlock Abyssal Drain will spam the ability in combat

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/127939494/3494efb9-5809-47e6-a879-e0fbfbb53cc4)

**Comment by adambennett55** [comment]
This happens to ALOT of class and alot of abilities! I have not looked at the Strucs in detail but is there no way to determine if the ability is not learned?

**Comment by NostraThomas99** [comment]
There is. I implemented it about a dozen versions ago. If it's trying to cast its because the game is saying it's possible to cast that spell. It could be there's something wrong with how we're using that check, though. I tested it on warrior and it stopped the action spam but other classes might be different?
